name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      - name: Build
        run: go build -v ./...
  

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
      - name: Go Format
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './src'
          gofmt-flags: '-l -d'
      - name: Test with the Go CLI
        run: go test ./pkg